### ISSUE TITLE
Stop chatters from being able to drop outside of the arena

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/get_the_streamer_game#12]
This doesn't cause problems, but it's not a great experience when chatters can drop something like a flame outside of the visible arena. The drop will still happen but nothing will display on screen obviously. We want to stop the drop from happening and respond with a message to chat letting them know that they need to drop on the screen.

**Comment by MeirKlemp** [comment]
I am working on it.

**Comment by MeirKlemp** [comment]
https://github.com/brooks-builds/get_the_streamer_game/blob/62f9ac209a5932126b192d0d55d4f6a5c0fb1b7b/src/interface.rs#L12
I am thinking of moving it to lib.rs and make it pub so I will be able to use it in command.rs.

**Comment by MeirKlemp** [comment]
Also, I don't know how to set up the application 😁. I managed to get a token but still, the game crashes...

**Comment by BrooksPatton** [comment]
We can take a look tomorrow morning during the stream. What is the address of your fork? Also, what Operating System are you using?

**Comment by MeirKlemp** [comment]
This is my [fork](https://github.com/MeirKlemp/get_the_streamer_game) and I am using Windows 10.
