### ISSUE TITLE
Game crashes when the streamer wins

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/get_the_streamer_game#13]
currently when the streamer wins due to the timer ending there is an underflow critical error that causes the game to crash. We want to catch that the timer has reached zero and then switch to a game over statement.

**Comment by MeirKlemp** [comment]
I think you fixed it

**Comment by BrooksPatton** [comment]
We'll find out this morning when I continue!

**Comment by BrooksPatton** [comment]
We tested this morning and the game didn't fully quit when I closed the game window.

**Comment by BrooksPatton** [comment]
I mistook this issue for #3 . You are correct @MeirKlemp this issue has been fixed.
