### ISSUE TITLE
Make swords fall out of arena instead of just dissapearing

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/get_the_streamer_game#19]
Currently the swords disappear after bouncing 7 times. This is a bit jarring, and we can do better by having the swords fall off the screen after their 7th hit and then die.

**Comment by MeirKlemp** [comment]
Hi, I would like to work on it.

**Comment by MeirKlemp** [comment]
It can't be closed
I don't know how to connect between the pr and the issue...
