### ISSUE TITLE
Stop using graphics::drawable_size to get window size

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/get_the_streamer_game#23]
We discovered a bug where if the screensize is 1920 x 1080 then the result of drawable_size is (1539.2, 844.0) which causes everything to be off math-wise.

We can store the screen size in game state and pass that around instead.

**Comment by MeirKlemp** [comment]
I would like to work on it.

**Comment by MeirKlemp** [comment]
You can close it
