### ISSUE TITLE
When quitting the app, exit all processes

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/get_the_streamer_game#3]
currently when we close the game, the chat thread is still running. It will crash on the message coming in. We need to catch that the program ended and then shut all of the threads down and exit properly.

**Comment by MeirKlemp** [comment]
I think in order to do that, the crate [twitch_chat_wrapper](https://github.com/brooks-builds/twitch_chat_wrapper) should be updated so it would be able to receive also a quit command instead of just chat messages.

**Comment by tsal** [comment]
I was looking into this while @MeirKlemp was replying - I think this can be done by using an `spmc` [channel](https://docs.rs/spmc/0.3.0/spmc/) and have each thread check that as part of their loop. if it gets a close, close down the thread(s).

**Comment by BrooksPatton** [comment]
I think that sounds like a good plan. I've deployed Twitch Chat Wrapper to crates.io, so it shouldn't be difficult to update and then get that update into the game.

**Comment by BrooksPatton** [comment]
thinking about it though, we aren't running any threads in the twitch chat wrapper crate.

Another thought, could we switch to async / await to help here?

**Comment by tsal** [comment]
> thinking about it though, we aren't running any threads in the twitch chat wrapper crate.
> 
> Another thought, could we switch to async / await to help here?

If we're not running any threads in the chat wrapper (sorry, I'm still learning Rust and haven't been through all the code!), then it's likely that async / await is all you need - but I think you're still going to need a channel?

**Comment by BrooksPatton** [comment]
I do have a channel that I'm sending to the Twitch Chat wrapper and receiving chat messages. Those are created in the main.rs file in this repo.

**Comment by BrooksPatton** [comment]
I'm going to start taking a look this morning.
