### ISSUE TITLE
Save score to disk

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/get_the_streamer_game#9]
Currently there is no scoring system, and the entire game resets as soon as the player wins/loses.

It would be really nice to keep track of chatters who have participated and give them points based on what they have done in the game.

* 1 point for dropping something
* 10 points for hitting the player

For right now since we don't have a database we'll want to store the scores in a file on the system that has the scores.

**Comment by BrooksPatton** [comment]
The crate savefile might be useful in saving the score to disk. (from Meirklemp)

**Comment by MeirKlemp** [comment]
The link: [savefile](https://crates.io/crates/savefile)
